name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: hospital
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres" 
          --health-interval=10s 
          --health-timeout=5s 
          --health-retries=5

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt

      - name: Run Alembic migrations
        env:
          DATABASE_URL: postgresql+asyncpg://postgres:postgres@localhost:5432/hospital
        run: |
          source .venv/bin/activate
          alembic upgrade head

      - name: Seed database via ETL
        env:
          DATABASE_URL: postgresql+asyncpg://postgres:postgres@localhost:5432/hospital
        run: |
          source .venv/bin/activate
          python etl.py

      - name: Start API (background)
        env:
          DATABASE_URL: postgresql+asyncpg://postgres:postgres@localhost:5432/hospital
        run: |
          source .venv/bin/activate
          nohup uvicorn app.main:app --host 0.0.0.0 --port 8000 &
          sleep 3

      - name: Smoke script
        run: |
          bash scripts/smoke.sh

      - name: Pytest
        env:
          BASE_URL: http://localhost:8000
        run: |
          source .venv/bin/activate
          pytest -q


